/**
 * Migration runner.
 *
 * Responsibilities: apply pending SQL migrations, exactly once, safely when more
 * than one process starts at the same time.
 * Dependencies: postgres, drizzle-orm.
 *
 * Connects as the migration role, not the application role (ADR-0015). That
 * separation is what lets the application be denied DDL, which in turn is what
 * makes the append-only ledger enforceable at the role level in slice 2.
 *
 * Migrations are plain SQL, generated by drizzle-kit and reviewed as SQL before
 * they land (ADR-0005 rule 2). Nothing here generates schema at runtime.
 */
import { drizzle } from 'drizzle-orm/postgres-js'
import { migrate as drizzleMigrate } from 'drizzle-orm/postgres-js/migrator'
import { sql } from 'drizzle-orm'
import postgres from 'postgres'

// ---------------------------------------------------------------------------
// Locking
// ---------------------------------------------------------------------------

/**
 * Advisory lock key. Arbitrary but fixed: any process using the same number is
 * cooperating on the same lock, and nothing else in the system uses this one.
 */
const MIGRATION_LOCK_KEY = 4_017_120_251

/**
 * Why an advisory lock at all.
 *
 * Deploys start several instances at once, and each runs migrations on boot.
 * Without a lock, two processes read the same "pending" list and both apply it.
 * The second usually fails on a duplicate object, but a data migration can
 * succeed twice, and applying a backfill twice to financial data is not
 * recoverable by rerunning it.
 *
 * `pg_advisory_lock` blocks rather than failing, so the second process waits and
 * then finds nothing to do. Session-scoped, so it is released explicitly in the
 * finally block below. It is also released automatically if the connection
 * drops, which is what stops a crashed deploy from wedging every later one.
 */
export type MigrationResult = {
  /** How long the run took, including waiting for the lock. */
  readonly durationMs: number
}

export class MigrationError extends Error {
  constructor(message: string, options?: { cause: unknown }) {
    super(message, options)
    this.name = 'MigrationError'
  }
}

// ---------------------------------------------------------------------------
// Running
// ---------------------------------------------------------------------------

/**
 * Apply pending migrations.
 *
 * Opens its own single connection rather than sharing the application pool: this
 * runs as a different role, runs once at boot, and must not consume a pooled
 * connection that request traffic needs.
 */
export async function runMigrations(options: {
  migrationUrl: string
  migrationsFolder: string
}): Promise<MigrationResult> {
  const startedAt = Date.now()

  // max: 1 because the advisory lock is session-scoped. On a larger pool the
  // unlock could be issued on a different connection than the lock, which
  // silently does nothing and leaves the lock held until the process exits.
  const client = postgres(options.migrationUrl, { max: 1, onnotice: () => undefined })
  const db = drizzle(client)

  try {
    await db.execute(sql`select pg_advisory_lock(${MIGRATION_LOCK_KEY})`)

    try {
      await drizzleMigrate(db, { migrationsFolder: options.migrationsFolder })
    } finally {
      // Released even if a migration throws, so a failed deploy does not block
      // the fix that follows it.
      await db.execute(sql`select pg_advisory_unlock(${MIGRATION_LOCK_KEY})`)
    }
  } catch (cause) {
    throw new MigrationError(
      'Migration failed. The database is unchanged past the last successful migration; ' +
        'fix the migration and run again.',
      { cause },
    )
  } finally {
    await client.end()
  }

  return { durationMs: Date.now() - startedAt }
}
