import postgres from 'postgres'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import { runMigrations } from '../migrate.js'
import { startTestDatabase, type TestDatabase } from '../testing/harness.js'

/**
 * Proves the schema enforces what the data model requires, against real
 * Postgres.
 *
 * A constraint is only real if the database rejects the violating write. These
 * tests attempt each violation and assert the rejection, because a constraint
 * that was mistyped in the schema file still typechecks and still generates
 * valid SQL.
 */

let container: TestDatabase
let sql: postgres.Sql

const MIGRATIONS = new URL('../../migrations', import.meta.url).pathname

beforeAll(async () => {
  container = await startTestDatabase()

  await runMigrations({ migrationUrl: container.migrationUrl, migrationsFolder: MIGRATIONS })

  // Superuser, so these tests can set up fixtures without fighting RLS. The
  // policies themselves are tested separately in rls.integration.test.ts, where
  // the application role is the point.
  sql = postgres(container.superuserUrl, { max: 1, onnotice: () => undefined })
}, 120_000)

afterAll(async () => {
  await sql.end()
  await container.stop()
})

/** Fresh ids per test, so one test's rows cannot satisfy another's assertion. */
async function createWorkspace(slug: string): Promise<string> {
  const [row] = await sql<{ id: string }[]>`
    insert into workspaces (slug, name) values (${slug}, ${slug}) returning id
  `
  return row?.id ?? ''
}

async function createUser(email: string): Promise<string> {
  const [row] = await sql<{ id: string }[]>`
    insert into users (email) values (${email}) returning id
  `
  return row?.id ?? ''
}

describe('migrations', () => {
  it('are idempotent, so a second deploy of the same version is a no-op', async () => {
    await expect(
      runMigrations({ migrationUrl: container.migrationUrl, migrationsFolder: MIGRATIONS }),
    ).resolves.toMatchObject({ durationMs: expect.any(Number) })
  })

  it('created every table the data model names for slice 1', async () => {
    const rows = await sql<{ table_name: string }[]>`
      select table_name from information_schema.tables
      where table_schema = 'public' and table_type = 'BASE TABLE'
      order by table_name
    `

    const names = rows.map((row) => row.table_name)

    expect(names).toContain('users')
    expect(names).toContain('workspaces')
    expect(names).toContain('workspace_members')
    expect(names).toContain('audit_logs')
  })
})

describe('primary keys', () => {
  // The data model requires UUIDv7 for index locality without leaking a
  // sequential count. Version nibble 7, variant in [89ab].
  it('are UUIDv7, generated by the database', async () => {
    const id = await createWorkspace('uuid-probe')

    expect(id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/)
  })

  it('are time ordered, which is the reason for v7 over v4', async () => {
    const first = await createWorkspace('order-probe-1')
    const second = await createWorkspace('order-probe-2')

    expect(second > first).toBe(true)
  })
})

describe('users.email', () => {
  it('is case insensitive, so one person cannot register twice', async () => {
    await createUser('Ada@example.com')

    await expect(createUser('ada@example.com')).rejects.toThrow(/duplicate key/i)
  })

  it('rejects an exact duplicate', async () => {
    await createUser('grace@example.com')

    await expect(createUser('grace@example.com')).rejects.toThrow(/duplicate key/i)
  })
})

describe('workspaces.slug', () => {
  // The slug becomes a storefront subdomain (ADR-0016), so two creators sharing
  // one differing only in case would collide in DNS.
  it('is case insensitive', async () => {
    await createWorkspace('Studio')

    await expect(createWorkspace('studio')).rejects.toThrow(/duplicate key/i)
  })
})

describe('workspace_members', () => {
  it('allows one membership per user per workspace', async () => {
    const workspace = await createWorkspace('members-unique')
    const user = await createUser('members-unique@example.com')

    await sql`insert into workspace_members (workspace_id, user_id) values (${workspace}, ${user})`

    await expect(
      sql`insert into workspace_members (workspace_id, user_id) values (${workspace}, ${user})`,
    ).rejects.toThrow(/duplicate key/i)
  })

  // Two owners is a governance problem, and the partial unique index is what
  // makes it impossible rather than merely validated against.
  it('permits exactly one owner per workspace', async () => {
    const workspace = await createWorkspace('one-owner')
    const first = await createUser('owner-1@example.com')
    const second = await createUser('owner-2@example.com')

    await sql`
      insert into workspace_members (workspace_id, user_id, role)
      values (${workspace}, ${first}, 'owner')
    `

    await expect(
      sql`
        insert into workspace_members (workspace_id, user_id, role)
        values (${workspace}, ${second}, 'owner')
      `,
    ).rejects.toThrow(/duplicate key/i)
  })

  it('permits many admins, since only owner is restricted', async () => {
    const workspace = await createWorkspace('many-admins')
    const first = await createUser('admin-1@example.com')
    const second = await createUser('admin-2@example.com')

    await sql`
      insert into workspace_members (workspace_id, user_id, role)
      values (${workspace}, ${first}, 'admin')
    `

    await expect(
      sql`
        insert into workspace_members (workspace_id, user_id, role)
        values (${workspace}, ${second}, 'admin')
      `,
    ).resolves.toBeDefined()
  })

  it('requires workspace_id, so a membership cannot exist outside a tenant', async () => {
    const user = await createUser('no-workspace@example.com')

    await expect(sql`insert into workspace_members (user_id) values (${user})`).rejects.toThrow(
      /null value|not-null/i,
    )
  })

  it('rejects a role outside the enum', async () => {
    const workspace = await createWorkspace('bad-role')
    const user = await createUser('bad-role@example.com')

    await expect(
      sql`
        insert into workspace_members (workspace_id, user_id, role)
        values (${workspace}, ${user}, 'superadmin')
      `,
    ).rejects.toThrow(/invalid input value for enum/i)
  })

  it('removes memberships when the workspace is deleted', async () => {
    const workspace = await createWorkspace('cascade-probe')
    const user = await createUser('cascade@example.com')

    await sql`insert into workspace_members (workspace_id, user_id) values (${workspace}, ${user})`
    await sql`delete from workspaces where id = ${workspace}`

    const remaining = await sql<{ count: number }[]>`
      select count(*)::int as count from workspace_members where workspace_id = ${workspace}
    `

    expect(remaining[0]?.count).toBe(0)
  })
})

describe('audit_logs', () => {
  it('accepts a platform action with no workspace', async () => {
    await expect(
      sql`insert into audit_logs (actor_type, action) values ('system', 'platform.started')`,
    ).resolves.toBeDefined()
  })

  // Deleting a workspace must not silently erase the record of what happened in
  // it. restrict rather than cascade, deliberately: the delete fails loudly and
  // a retention decision has to be made explicitly.
  it('blocks deleting a workspace that has audit history', async () => {
    const workspace = await createWorkspace('audit-restrict')

    await sql`
      insert into audit_logs (workspace_id, actor_type, action)
      values (${workspace}, 'user', 'workspace.created')
    `

    // 23001 is restrict_violation, which Postgres raises specifically for a
    // RESTRICT breach. A plain foreign key violation would be 23503, so the
    // code distinguishes "blocked by RESTRICT" from "no such parent row" and
    // proves the ON DELETE clause is doing the work rather than the reference.
    await expect(sql`delete from workspaces where id = ${workspace}`).rejects.toMatchObject({
      code: '23001',
    })
  })

  it('does not constrain actor_id by a foreign key, so history survives a deleted actor', async () => {
    const workspace = await createWorkspace('audit-actor')

    await expect(
      sql`
        insert into audit_logs (workspace_id, actor_type, actor_id, action)
        values (${workspace}, 'user', gen_random_uuid(), 'thing.happened')
      `,
    ).resolves.toBeDefined()
  })

  it('defaults metadata to an empty object rather than null', async () => {
    const [row] = await sql<{ metadata: unknown }[]>`
      insert into audit_logs (actor_type, action) values ('system', 'metadata.probe')
      returning metadata
    `

    expect(row?.metadata).toEqual({})
  })
})
