/**
 * Identity and tenancy tables.
 *
 * Responsibilities: define `users`, `workspaces`, `workspace_members`, and
 * `audit_logs` exactly as `docs/architecture/data-model.md` section 2 and
 * section 10 specify.
 * Dependencies: drizzle-orm. No application logic.
 *
 * Conventions applied here come from the data model and are not restated per
 * column: UUIDv7 primary keys, `TIMESTAMPTZ` stored UTC, `workspace_id NOT NULL`
 * on every tenant table, `created_at` and `updated_at` everywhere, `snake_case`
 * plural table names, and Postgres enums so invalid states are unrepresentable
 * at the storage layer.
 *
 * `users` is deliberately *not* tenant-scoped. A person can belong to several
 * workspaces, so the row cannot carry one workspace id. That makes it the one
 * table in this file the RLS work in 1.3 treats differently, and the reason is
 * recorded on the table rather than left to be rediscovered.
 */
import { sql } from 'drizzle-orm'
import {
  boolean,
  customType,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

// ---------------------------------------------------------------------------
// Shared column builders
//
// Repeating these by hand is how one table ends up with a subtly different
// timestamp type, which then breaks a comparison months later.
// ---------------------------------------------------------------------------

/** UUIDv7, generated by Postgres 18 natively. See ADR-0015. */
const primaryKey = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`)

const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow()

const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()

/**
 * Case-insensitive text, so `Ada@example.com` and `ada@example.com` cannot both
 * be registered.
 *
 * A real `citext` column, not `text`. Lowercasing in application code before
 * insert would leave the uniqueness guarantee dependent on every future call
 * site remembering to do it, and a unique index on `lower(email)` cannot be
 * referenced by a foreign key. The extension is created by the init script,
 * because creating one needs privileges the migration role does not have
 * (ADR-0015).
 */
const citext = customType<{ data: string }>({
  dataType: () => 'citext',
})

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const workspaceRole = pgEnum('workspace_role', ['owner', 'admin', 'member'])

export const workspaceStatus = pgEnum('workspace_status', ['active', 'suspended', 'deleted'])

export const auditActorType = pgEnum('audit_actor_type', [
  'user',
  'system',
  'affiliate',
  'api_key',
  'provider',
])

// ---------------------------------------------------------------------------
// users
// ---------------------------------------------------------------------------

/**
 * Global, not tenant-scoped.
 *
 * One person may be an owner of one workspace and a member of another, so there
 * is no single `workspace_id` this row could carry. Access is therefore
 * constrained by membership rather than by the tenant predicate, and the RLS
 * policy in 1.3 keys off "is there a shared workspace" rather than a direct
 * column comparison.
 *
 * The auth library owns `sessions`, `accounts`, `verification_tokens`, and
 * `passkeys` in this same database (ADR-0006). Those tables arrive in 1.6 and
 * are deliberately not declared here, because declaring a table the library
 * also migrates produces two sources of truth for one schema.
 */
export const users = pgTable(
  'users',
  {
    id: primaryKey(),
    email: citext('email').notNull(),

    /**
     * When the address was verified, and the authoritative answer to whether it
     * was. Nullable because an unverified user is a real state.
     */
    emailVerifiedAt: timestamp('email_verified_at', { withTimezone: true }),

    /**
     * The boolean Better Auth requires, kept in step with the timestamp by the
     * trigger in migration 0004. See ADR-0018.
     *
     * Do not write this from application code. Reading it is fine and cheap;
     * writing it bypasses nothing, because the trigger will still set the
     * timestamp, but it does put the decision in two places. Verification flows
     * go through `packages/auth`.
     */
    emailVerified: boolean('email_verified').notNull().default(false),

    name: text('name'),
    avatarUrl: text('avatar_url'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [uniqueIndex('uq_users__email').on(table.email)],
)

// ---------------------------------------------------------------------------
// workspaces
// ---------------------------------------------------------------------------

/**
 * The tenant root, and the unit of billing, isolation, and ownership.
 *
 * `slug` becomes the storefront subdomain at `{slug}.creatorhub.com`
 * (ADR-0016), which is why it is checked against a reserved-word denylist
 * before insert rather than only being unique. `www.creatorhub.com` belonging to
 * a creator would be a problem no constraint here can undo.
 */
export const workspaces = pgTable(
  'workspaces',
  {
    id: primaryKey(),
    slug: citext('slug').notNull(),
    name: text('name').notNull(),
    timezone: text('timezone').notNull().default('Asia/Kolkata'),

    /**
     * ISO 4217, three uppercase letters. INR by default per ADR-0016.
     * Stored as the code alone; amounts carry their own currency alongside the
     * `bigint` minor units, so this is the default for new prices rather than a
     * global truth.
     */
    defaultCurrency: text('default_currency').notNull().default('INR'),

    /**
     * Platform fee in basis points. 500 = 5.00%, 250 = 2.50%.
     * Deducted from every sale before the creator receives their payout.
     * Configurable per workspace so high-volume creators can negotiate lower rates.
     */
    platformFeeBps: integer('platform_fee_bps').notNull().default(500),

    status: workspaceStatus('status').notNull().default('active'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [uniqueIndex('uq_workspaces__slug').on(table.slug)],
)

// ---------------------------------------------------------------------------
// workspace_members
// ---------------------------------------------------------------------------

/**
 * Which users may act in which workspace, and with what authority.
 *
 * Every authorisation check in the system answers one question from this table:
 * does this user hold a role in this workspace sufficient for this action? The
 * policy module in 1.8 derives permissions from `role` in one place;
 * permissions inlined into route handlers are how tenancy leaks happen.
 */
export const workspaceMembers = pgTable(
  'workspace_members',
  {
    id: primaryKey(),
    workspaceId: uuid('workspace_id')
      .notNull()
      .references(() => workspaces.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: workspaceRole('role').notNull().default('member'),
    invitedByUserId: uuid('invited_by_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    joinedAt: timestamp('joined_at', { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    uniqueIndex('uq_workspace_members__workspace_user').on(table.workspaceId, table.userId),

    // Exactly one owner per workspace, enforced by a partial unique index
    // rather than by application code. Two owners is a governance problem no
    // validation function can be trusted to prevent forever.
    uniqueIndex('uq_workspace_members__one_owner')
      .on(table.workspaceId)
      .where(sql`role = 'owner'`),

    // "Which workspaces does this user belong to" is on the path of every
    // authenticated request.
    index('idx_workspace_members__user').on(table.userId),
  ],
)

// ---------------------------------------------------------------------------
// audit_logs
// ---------------------------------------------------------------------------

/**
 * Append-only record of every state change to money, entitlements, and
 * permissions.
 *
 * This is the table that answers a dispute, a security question, or a
 * regulator. It cannot be reconstructed after the fact, which is why it exists
 * in M1 rather than when it is first needed.
 *
 * `workspace_id` is nullable because platform-level actions have no workspace.
 * That makes it the one tenant table whose RLS policy must also admit
 * `workspace_id IS NULL` for the platform role, and 1.3 handles it explicitly.
 *
 * The append-only constraint is enforced in 1.10 by a rule that rejects UPDATE
 * and DELETE, the same mechanism ADR-0008 uses for `ledger_entries`. Declaring
 * the table without that rule would leave a window where history is editable,
 * so 1.10 follows immediately.
 */
export const auditLogs = pgTable(
  'audit_logs',
  {
    id: primaryKey(),
    workspaceId: uuid('workspace_id').references(() => workspaces.id, { onDelete: 'restrict' }),

    actorType: auditActorType('actor_type').notNull(),

    /**
     * Not a foreign key. An actor may be a user, an affiliate, an API key, or a
     * provider, and the row must survive the deletion of whatever it points at.
     * Financial history that disappears when a user is deleted is not evidence.
     */
    actorId: uuid('actor_id'),

    /** Dotted, past tense: `order.refunded`, `member.role_changed`. */
    action: text('action').notNull(),

    targetType: text('target_type'),
    targetId: uuid('target_id'),

    metadata: jsonb('metadata')
      .notNull()
      .default(sql`'{}'::jsonb`),

    /**
     * Hashed with a rotating salt at write time, never raw. A log of who did
     * what is not a reason to hold an address indefinitely.
     */
    ipHash: text('ip_hash'),
    userAgent: text('user_agent'),

    /** Correlates every row written while serving one request. */
    requestId: text('request_id'),

    occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index('idx_audit_logs__workspace_occurred').on(table.workspaceId, table.occurredAt),
    index('idx_audit_logs__target').on(table.targetType, table.targetId),
    index('idx_audit_logs__actor').on(table.actorType, table.actorId),
  ],
)

// ---------------------------------------------------------------------------
// Tenant table registry
//
// The CI check in 1.5 reads this list and fails the build if a table named here
// lacks `workspace_id` or an RLS policy. Adding a tenant table means adding it
// here, and forgetting is a failed build rather than a silent hole.
// ---------------------------------------------------------------------------

export const TENANT_TABLES = ['workspace_members', 'audit_logs'] as const

/**
 * Tables that legitimately have no `workspace_id`, with the reason. Anything not
 * in this list and not in TENANT_TABLES fails the CI check, so a new table
 * cannot quietly avoid both.
 */
export const NON_TENANT_TABLES = {
  users: 'A person may belong to several workspaces, so no single workspace owns the row.',
  workspaces: 'This is the tenant root. It is identified by id, not scoped by one.',
} as const
